### ISSUE TITLE
Deploying to IIS

### ISSUE THREAD

**Issue by mark-mngoma** [jhipster/jhipster-net-sample-app-template#34] opened 2020-09-01 10:11 UTC
I am encountering **500.36 ANCM Out-Of-Process Handler Load Failure**, please assist with a guide on how to deploy to IIS Server as I think the issue is based around Serilog, because when I remove logging, it works.

**Comment by nicolas63** [comment] 2020-09-01 19:47
Yes i will try to reproduce as soon as possible but open or comment PR on https://github.com/jhipster/jhipster-dotnetcore because this repo is deprecated. So i close this issue

**Closed as completed by nicolas63** 2020-09-01 19:47 UTC
